//! Generated grants: the subject permissions every user JWT ck-bus builds carries.
//!
//! Every subject comes from `cortexkit-bus-naming`. This area picks the set for a role
//! (participant, bus module, system account), checks it with the naming crate's own
//! permission-file validator, and shapes it as the allow-only `pub`/`sub` lists of a
//! NATS user JWT. It writes no subject of its own.
//!
//! The same generator, fed the fixed fixture identities the naming crate pins for its
//! reference document (`PINNED_GOLDEN_FIXTURE`), renders a permission document. The
//! tests compare it with prefrontal's committed reference copy (vendored as
//! `tests/fixtures/foundation/permission_golden.txt`): it may differ only in the header
//! line and in added subjects that are named explicitly (the golden diff rule in
//! `docs/specs/ck-bus-module.md`).

use std::{collections::BTreeSet, error::Error, fmt};

use cortexkit_bus_naming::{
    bus_permissions, delivery_authority_permissions, flow_engine_permissions,
    generate_permission_golden, participant_permissions, system_permissions,
    validate_permission_file, AccountNames, AllowEntry, GoldenFixture, GrantError, NamingError,
    Operation, Principal,
};
use serde_json::{json, Value};

/// The first line of a document this generator renders. It names this generator, so it
/// is the one line allowed to differ from the committed reference document's header.
pub const GENERATOR_HEADER: &str =
    "# Generated by ck-bus grants from cortexkit-bus-naming; edit the generator, not this file.";

/// Which user a grant is for. Each role maps to one principal of the naming crate's
/// permission model.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum GrantRole {
    /// A supervised participant's per-process user in the box account.
    Participant,
    /// prefrontal-core's per-process user: the participant set plus publish on every
    /// agent stream's binding and on the ROOM binding, and its one ROOM durable (R15).
    DeliveryAuthority,
    /// The flow engine's (basal's) per-process user: its own durable on the event
    /// stream, ephemeral ordered consumers there for dry-run replay, census read and the
    /// dead-letter publish. No workload publish and no agent durable.
    FlowEngine,
    /// ck-bus's own user in the box account.
    BusModule,
    /// ck-bus's own user in the system account.
    SystemAccount,
}

impl GrantRole {
    pub const fn principal(self) -> Principal {
        match self {
            Self::Participant => Principal::Participant,
            Self::DeliveryAuthority => Principal::DeliveryAuthority,
            Self::FlowEngine => Principal::FlowEngine,
            Self::BusModule => Principal::Bus,
            Self::SystemAccount => Principal::System,
        }
    }
}

/// Why a grant or a rendered document was refused. A refused grant is never issued.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GrantRefusal {
    /// The naming crate refused an input token or the permission shape.
    Generator(GrantError),
    /// An entry was generated for a different principal than the grant's role.
    WrongPrincipal {
        role: GrantRole,
        found: Principal,
        subject: String,
    },
    /// A role produced no allow entry at all, which would issue a user that can do nothing
    /// and hides a generator fault.
    Empty { role: GrantRole },
}

impl fmt::Display for GrantRefusal {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Generator(error) => write!(f, "grant generation refused: {error}"),
            Self::WrongPrincipal {
                role,
                found,
                subject,
            } => write!(
                f,
                "grant for {role:?} carries an entry for principal {} on {subject}",
                found.as_str()
            ),
            Self::Empty { role } => write!(f, "grant for {role:?} has no allow entry"),
        }
    }
}

impl Error for GrantRefusal {}

impl From<GrantError> for GrantRefusal {
    fn from(value: GrantError) -> Self {
        Self::Generator(value)
    }
}

impl From<NamingError> for GrantRefusal {
    fn from(value: NamingError) -> Self {
        Self::Generator(GrantError::Naming(value))
    }
}

/// One role's checked, allow-only permission set. There is no deny list: absence from
/// the allow lists is the denial, and the type has nowhere to put a deny entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Grant {
    role: GrantRole,
    account: String,
    publish: BTreeSet<String>,
    subscribe: BTreeSet<String>,
}

impl Grant {
    /// Builds a grant from generated entries, refusing it unless every entry belongs to
    /// the role's principal and passes the naming crate's permission-file validator
    /// (allow-only, whole-token wildcards, no unexpanded placeholders).
    pub fn from_entries(
        role: GrantRole,
        account: &AccountNames,
        entries: Vec<AllowEntry>,
    ) -> Result<Self, GrantRefusal> {
        if entries.is_empty() {
            return Err(GrantRefusal::Empty { role });
        }
        let mut publish = BTreeSet::new();
        let mut subscribe = BTreeSet::new();
        for entry in &entries {
            if entry.principal != role.principal() {
                return Err(GrantRefusal::WrongPrincipal {
                    role,
                    found: entry.principal,
                    subject: entry.subject.clone(),
                });
            }
            match entry.operation {
                Operation::Publish => publish.insert(entry.subject.clone()),
                Operation::Subscribe => subscribe.insert(entry.subject.clone()),
            };
        }
        validate_role_entries(&entries, account)?;
        Ok(Self {
            role,
            account: account.account().to_owned(),
            publish,
            subscribe,
        })
    }

    pub fn role(&self) -> GrantRole {
        self.role
    }

    /// The account token the grant was derived for. The system-account grant names no
    /// box subject, but it is still generated for (and checked against) one box.
    pub fn account(&self) -> &str {
        &self.account
    }

    pub fn publish_allow(&self) -> &BTreeSet<String> {
        &self.publish
    }

    pub fn subscribe_allow(&self) -> &BTreeSet<String> {
        &self.subscribe
    }

    /// The grant as permission-model entries, in the naming crate's sort order.
    pub fn allow_entries(&self) -> Vec<AllowEntry> {
        let principal = self.role.principal();
        let publish = self.publish.iter().map(|subject| AllowEntry {
            principal,
            operation: Operation::Publish,
            subject: subject.clone(),
        });
        let subscribe = self.subscribe.iter().map(|subject| AllowEntry {
            principal,
            operation: Operation::Subscribe,
            subject: subject.clone(),
        });
        publish.chain(subscribe).collect()
    }

    /// The `pub` and `sub` members of a NATS user JWT's `nats` claim. Only `allow` lists
    /// are emitted; a `deny` list would carve exceptions out of a broader allow, which the
    /// foundation forbids.
    pub fn jwt_permissions(&self) -> Value {
        json!({
            "pub": { "allow": self.publish.iter().collect::<Vec<_>>() },
            "sub": { "allow": self.subscribe.iter().collect::<Vec<_>>() },
        })
    }
}

/// Derives the account names for `{acct}`, refusing a token outside the account lexicon
/// with that token named.
pub fn derive_account(account: &str) -> Result<AccountNames, GrantRefusal> {
    Ok(AccountNames::derive(account)?)
}

/// The per-process grant for participant `module_id` bound to `bound_rooms`. It names
/// no agent: it may pull, inspect and ack any agent's durable on the agent streams, and
/// publishes no workload subject. It publishes module events on its own event subjects
/// (`ck.{acct}.event.{module_id}.>`) and on no other module's. `credential_public` is
/// the user's public key, which names its inbox prefix.
pub fn participant_grant(
    account: &AccountNames,
    credential_public: &str,
    module_id: &str,
    bound_rooms: &[&str],
) -> Result<Grant, GrantRefusal> {
    let entries = participant_permissions(account, credential_public, module_id, bound_rooms)?;
    Grant::from_entries(GrantRole::Participant, account, entries)
}

/// prefrontal-core's per-process grant: the participant set plus publish on each agent
/// stream's own binding and on the ROOM binding, since it is the only producer of wakes,
/// peer deliveries, effect intents and room posts, and pull, ack and info on its one
/// ROOM durable `m_{module_id}`, which bootstrap creates.
pub fn delivery_authority_grant(
    account: &AccountNames,
    credential_public: &str,
    module_id: &str,
    bound_rooms: &[&str],
) -> Result<Grant, GrantRefusal> {
    let entries =
        delivery_authority_permissions(account, credential_public, module_id, bound_rooms)?;
    Grant::from_entries(GrantRole::DeliveryAuthority, account, entries)
}

/// The flow engine's per-process grant: pull, ack and info on its own durable
/// `m_{module_id}` on the event stream (which bootstrap creates), unnamed consumer create,
/// consumer info and flow control on that stream for its dry-run replays, census read and
/// the dead-letter publish. It publishes no workload subject and reads no agent durable.
pub fn flow_engine_grant(
    account: &AccountNames,
    credential_public: &str,
    module_id: &str,
) -> Result<Grant, GrantRefusal> {
    let entries = flow_engine_permissions(account, credential_public, module_id)?;
    Grant::from_entries(GrantRole::FlowEngine, account, entries)
}

/// The module whose attested credential carries the delivery-authority grant (R15):
/// prefrontal publishes to every agent and to every room, and reads room posts through
/// its ROOM durable.
pub const DELIVERY_AUTHORITY_MODULE: &str = "prefrontal-core";

/// The module whose attested credential carries the flow-engine grant: basal runs flows
/// and reads every module event through its event-stream durable.
pub const FLOW_ENGINE_MODULE: &str = "basal";

/// The grant issuance signs for the attested `module_id`. No form names an agent: R15
/// makes agent access account-scoped, so a module's residence can change without a
/// reissue.
///
/// `prefrontal-core` gets the delivery-authority grant, `basal` the flow-engine grant,
/// and every other module the participant grant. `module_id` is the daemon-attested
/// route principal, never a request field: it also decides which event subjects the
/// credential may publish on.
pub fn issued_grant(
    account: &AccountNames,
    module_id: &str,
    credential_public: &str,
    bound_rooms: &[&str],
) -> Result<Grant, GrantRefusal> {
    match module_id {
        DELIVERY_AUTHORITY_MODULE => {
            delivery_authority_grant(account, credential_public, module_id, bound_rooms)
        }
        FLOW_ENGINE_MODULE => flow_engine_grant(account, credential_public, module_id),
        _ => participant_grant(account, credential_public, module_id, bound_rooms),
    }
}

/// ck-bus's own box-account grant: census read and write, management of the six
/// streams and their consumers (the dead-letter durable and the module durables among
/// them), and the sentinel subjects. No workload publish.
pub fn bus_module_grant(
    account: &AccountNames,
    credential_public: &str,
) -> Result<Grant, GrantRefusal> {
    let entries = bus_permissions(account, credential_public)?;
    Grant::from_entries(GrantRole::BusModule, account, entries)
}

/// ck-bus's system-account grant: the claims update, the claims list and per-account
/// lookup, the kick, the connect and disconnect events, and the user's own inbox
/// (`_INBOX.<credential_public>.>`) for the replies, as the naming crate enumerates
/// them.
pub fn system_account_grant(
    account: &AccountNames,
    credential_public: &str,
) -> Result<Grant, GrantRefusal> {
    let entries = system_permissions(credential_public)?;
    Grant::from_entries(GrantRole::SystemAccount, account, entries)
}

/// Renders the permission document for a golden fixture from the five role grants.
///
/// The fixture has no real user key, so each role's module id stands in where a
/// credential public key goes: the participant's and bus module's inbox subjects read
/// `_INBOX.<module id>.>`, the delivery authority's `_INBOX.<delivery_authority_module>.>`,
/// the flow engine's `_INBOX.<flow_engine_module>.>`, and the system user's
/// `_INBOX.<system_credential>.>`, exactly as in the committed reference document. The
/// `expect-refused` lines are the naming crate's own expectations for the same fixture;
/// ck-bus adds none and drops none. The result is checked with the same validator the
/// naming crate applies to its golden, so a partial-token wildcard or a `deny` line
/// never leaves this function.
pub fn render_fixture_document(fixture: GoldenFixture) -> Result<String, GrantRefusal> {
    let account = derive_account(fixture.account)?;
    let grants = [
        participant_grant(
            &account,
            fixture.module_id,
            fixture.module_id,
            &[fixture.bound_room],
        )?,
        delivery_authority_grant(
            &account,
            fixture.delivery_authority_module,
            fixture.delivery_authority_module,
            &[fixture.bound_room],
        )?,
        bus_module_grant(&account, fixture.module_id)?,
        system_account_grant(&account, fixture.system_credential)?,
        flow_engine_grant(
            &account,
            fixture.flow_engine_module,
            fixture.flow_engine_module,
        )?,
    ];
    let expectations = generate_permission_golden(fixture)?;

    let allows = grants
        .iter()
        .flat_map(Grant::allow_entries)
        .collect::<BTreeSet<_>>();

    let mut output = format!("{GENERATOR_HEADER}\n");
    for (name, value) in [
        ("account", fixture.account),
        ("module", fixture.module_id),
        ("bound-agent", fixture.bound_agent),
        ("foreign-agent", fixture.foreign_agent),
        ("bound-room", fixture.bound_room),
        ("unbound-room", fixture.unbound_room),
        ("flow-engine-module", fixture.flow_engine_module),
        ("foreign-module", fixture.foreign_module),
        (
            "delivery-authority-module",
            fixture.delivery_authority_module,
        ),
    ] {
        output.push_str(&format!("fixture {name} {value}\n"));
    }
    output.push('\n');
    for entry in &allows {
        output.push_str(&format!(
            "allow {} {} {}\n",
            entry.principal.as_str(),
            entry.operation.as_str(),
            entry.subject
        ));
    }
    output.push('\n');
    for entry in expectations.refused() {
        output.push_str(&format!(
            "expect-refused {} {} {} {}\n",
            entry.principal.as_str(),
            entry.operation.as_str(),
            entry.subject,
            entry.reason
        ));
    }
    validate_document(&output, &account)?;
    Ok(output)
}

/// Checks a whole permission document: allow-only, whole-token wildcards, and every one
/// of the account's six literal stream names expanded somewhere.
pub fn validate_document(contents: &str, account: &AccountNames) -> Result<(), GrantRefusal> {
    Ok(validate_permission_file(contents, account)?)
}

/// Checks one role's entries with the naming crate's permission-file validator. A single
/// role legitimately does not expand all six streams (a participant never names the
/// dead-letter stream), so only the stream-expansion finding is waived here; the whole
/// document is held to it by `validate_document`.
fn validate_role_entries(
    entries: &[AllowEntry],
    account: &AccountNames,
) -> Result<(), GrantRefusal> {
    let mut contents = String::new();
    for entry in entries {
        contents.push_str(&format!(
            "allow {} {} {}\n",
            entry.principal.as_str(),
            entry.operation.as_str(),
            entry.subject
        ));
    }
    match validate_permission_file(&contents, account) {
        Ok(()) | Err(GrantError::MissingStreamExpansion { .. }) => Ok(()),
        Err(error) => Err(error.into()),
    }
}

impl Grant {
    /// The generated grant as the runtime seam carries it.
    pub fn generated(&self) -> crate::runtime::GeneratedGrant {
        crate::runtime::GeneratedGrant {
            publish: self.publish.clone(),
            subscribe: self.subscribe.clone(),
        }
    }

    /// Rebuilds a grant from what the runtime seam returned, re-checking every entry
    /// exactly as a freshly generated grant is checked.
    pub fn from_generated(
        role: GrantRole,
        account: &AccountNames,
        generated: &crate::runtime::GeneratedGrant,
    ) -> Result<Self, GrantRefusal> {
        let principal = role.principal();
        let entries = generated
            .publish
            .iter()
            .map(|subject| (Operation::Publish, subject))
            .chain(
                generated
                    .subscribe
                    .iter()
                    .map(|subject| (Operation::Subscribe, subject)),
            )
            .map(|(operation, subject)| AllowEntry {
                principal,
                operation,
                subject: subject.clone(),
            })
            .collect();
        Self::from_entries(role, account, entries)
    }
}

/// The runtime's grant-generation seam as wired at start. Bootstrap passes the box
/// account (derived from the HELLO_ACK machine id) and the user's public key, and gets
/// back the grant the naming crate generates for that user.
pub struct GrantSeam;

impl crate::runtime::GrantGeneration for GrantSeam {
    fn own_user_grant(
        &self,
        user: crate::runtime::OwnUser,
        account: &AccountNames,
        user_public: &str,
    ) -> Result<crate::runtime::GeneratedGrant, crate::runtime::GrantSeamError> {
        let grant = match user {
            crate::runtime::OwnUser::BusModule => bus_module_grant(account, user_public),
            crate::runtime::OwnUser::SystemAccount => system_account_grant(account, user_public),
        };
        grant
            .map(|grant| grant.generated())
            .map_err(|refusal| crate::runtime::GrantSeamError::Refused(refusal.to_string()))
    }
}
