//! Ladder row "Grant generation" (slice 2). served-by: none -- the row opens no
//! Claustrum or Callosum route and starts no server.
//!
//! The generator in `src/grants`, fed the fixed fixture identities the foundation pins
//! (`PINNED_GOLDEN_FIXTURE`), emits the participant, bus-module and system-account
//! permission sets. Rendered as a document, they must equal the naming crate's committed
//! reference document `permission_golden.txt` (commons, vendored under
//! `tests/fixtures/foundation/`) except for the header line and the subjects named in
//! `ADDED_SUBJECTS`. The controls show that a partial-token wildcard, a `deny` entry and
//! an out-of-lexicon account are each refused.

#[allow(dead_code)]
#[path = "../src/grants/mod.rs"]
mod grants;
#[allow(dead_code)]
mod harness;
// The grant area implements a runtime seam, so it names `crate::runtime`; this gives it
// the seam definitions without the rest of the binary.
#[allow(dead_code)]
#[path = "../src/runtime/seams.rs"]
mod runtime;

use std::{collections::BTreeSet, fs, path::PathBuf};

use cortexkit_bus_naming::{AllowEntry, GrantError, Operation, Principal, PINNED_GOLDEN_FIXTURE};
use grants::{GrantRefusal, GrantRole};
use harness::data_home;
use sha2::{Digest, Sha256};

const ROW: &str = "Grant generation";
const SERVED_BY: &str = "none";

/// Subjects the ck-bus generator emits beyond the vendored golden. The golden diff rule
/// allows additions only when each is named; this row adds none.
const ADDED_SUBJECTS: &[&str] = &[];

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/foundation")
}

fn read_fixture(name: &str) -> String {
    let path = fixture_dir().join(name);
    fs::read_to_string(&path).unwrap_or_else(|error| panic!("read {}: {error}", path.display()))
}

fn vendored_golden() -> String {
    read_fixture("permission_golden.txt")
}

fn report(outcome: &str, detail: &str) {
    eprintln!(
        "{}",
        serde_json::json!({
            "row": ROW,
            "served_by": SERVED_BY,
            "outcome": outcome,
            "detail": detail,
        })
    );
}

/// Applies the golden diff rule: the first line of each document is its generator
/// header and must name a generator; every other vendored line appears unchanged and in
/// order in the regenerated document; any extra regenerated line is an `allow` line.
/// Returns the added subjects.
fn golden_diff(vendored: &str, regenerated: &str) -> Result<Vec<String>, String> {
    let mut vendored_lines = vendored.lines();
    let mut regenerated_lines = regenerated.lines();
    let vendored_header = vendored_lines.next().ok_or("vendored golden is empty")?;
    let regenerated_header = regenerated_lines
        .next()
        .ok_or("regenerated document is empty")?;
    for header in [vendored_header, regenerated_header] {
        if !header.starts_with("# Generated by ") {
            return Err(format!("header line does not name a generator: {header:?}"));
        }
    }

    let mut added = Vec::new();
    let mut pending = vendored_lines.peekable();
    for line in regenerated_lines {
        if pending.peek() == Some(&line) {
            pending.next();
            continue;
        }
        match line.split_whitespace().collect::<Vec<_>>().as_slice() {
            ["allow", _, _, subject] => added.push((*subject).to_owned()),
            _ => {
                return Err(format!(
                    "regenerated line is neither golden nor an added allow: {line:?}"
                ))
            }
        }
    }
    if let Some(missing) = pending.next() {
        return Err(format!("golden line removed or modified: {missing:?}"));
    }
    Ok(added)
}

/// NATS subject matching with whole-token wildcards: `*` matches one token, a final `>`
/// matches one or more.
fn subject_matches(pattern: &str, subject: &str) -> bool {
    let pattern = pattern.split('.').collect::<Vec<_>>();
    let subject = subject.split('.').collect::<Vec<_>>();
    for (index, token) in pattern.iter().enumerate() {
        if *token == ">" {
            return subject.len() > index;
        }
        match subject.get(index) {
            Some(value) if *token == "*" || token == value => {}
            _ => return false,
        }
    }
    pattern.len() == subject.len()
}

fn golden_allows(golden: &str, principal: Principal, operation: Operation) -> BTreeSet<String> {
    golden
        .lines()
        .filter_map(
            |line| match line.split_whitespace().collect::<Vec<_>>().as_slice() {
                ["allow", p, o, subject]
                    if *p == principal.as_str() && *o == operation.as_str() =>
                {
                    Some((*subject).to_owned())
                }
                _ => None,
            },
        )
        .collect()
}

#[test]
fn grant_generation_matches_vendored_golden_under_the_diff_rule() {
    let operator_dir = data_home::operator_module_dir();
    let operator_before = data_home::fingerprint(operator_dir.as_deref());

    let regenerated = grants::render_fixture_document(PINNED_GOLDEN_FIXTURE)
        .expect("the pinned golden literals must generate");
    let vendored = vendored_golden();
    assert_eq!(
        regenerated.lines().next(),
        Some(grants::GENERATOR_HEADER),
        "the regenerated document must carry the ck-bus generator header"
    );
    assert_ne!(
        regenerated.lines().next(),
        vendored.lines().next(),
        "the header line is the one line that names a different generator"
    );
    let added = golden_diff(&vendored, &regenerated)
        .unwrap_or_else(|error| panic!("golden diff rule violated: {error}"));
    assert_eq!(
        added, ADDED_SUBJECTS,
        "every subject added beyond the vendored golden must be named in ADDED_SUBJECTS"
    );

    assert_eq!(
        data_home::fingerprint(operator_dir.as_deref()),
        operator_before,
        "the row must write nothing under the operator's real data home"
    );
    report(
        "passed",
        "regenerated golden differs in the header line only; added subjects: none",
    );
}

#[test]
fn grant_generation_emits_each_role_set_from_the_pinned_literals() {
    let fixture = PINNED_GOLDEN_FIXTURE;
    let golden = vendored_golden();
    let account = grants::derive_account(fixture.account).expect("pinned account derives");
    let participant = grants::participant_grant(
        &account,
        fixture.module_id,
        fixture.module_id,
        &[fixture.bound_room],
    )
    .expect("participant grant");
    let delivery = grants::delivery_authority_grant(
        &account,
        fixture.delivery_authority_module,
        fixture.delivery_authority_module,
        &[fixture.bound_room],
    )
    .expect("delivery-authority grant");
    let bus = grants::bus_module_grant(&account, fixture.module_id).expect("bus-module grant");
    let system = grants::system_account_grant(&account, fixture.system_credential)
        .expect("system-account grant");
    let flow_engine = grants::flow_engine_grant(
        &account,
        fixture.flow_engine_module,
        fixture.flow_engine_module,
    )
    .expect("flow-engine grant");

    for grant in [&participant, &delivery, &bus, &system, &flow_engine] {
        let principal = grant.role().principal();
        assert_eq!(
            grant.publish_allow(),
            &golden_allows(&golden, principal, Operation::Publish),
            "{:?} publish set must equal the golden's {} publish lines",
            grant.role(),
            principal.as_str()
        );
        assert_eq!(
            grant.subscribe_allow(),
            &golden_allows(&golden, principal, Operation::Subscribe),
            "{:?} subscribe set must equal the golden's {} subscribe lines",
            grant.role(),
            principal.as_str()
        );

        let claim = grant.jwt_permissions();
        let claim = claim.as_object().expect("permissions claim is an object");
        assert_eq!(
            claim.keys().collect::<Vec<_>>(),
            ["pub", "sub"],
            "the JWT permissions carry only pub and sub"
        );
        for (direction, subjects) in [
            ("pub", grant.publish_allow()),
            ("sub", grant.subscribe_allow()),
        ] {
            let lists = claim[direction]
                .as_object()
                .expect("direction is an object");
            assert_eq!(
                lists.keys().collect::<Vec<_>>(),
                ["allow"],
                "{:?} {direction} must carry an allow list and no deny list",
                grant.role()
            );
            let allow = lists["allow"]
                .as_array()
                .expect("allow is a list")
                .iter()
                .map(|value| value.as_str().expect("subject string").to_owned())
                .collect::<BTreeSet<_>>();
            assert_eq!(
                &allow,
                subjects,
                "{:?} {direction} allow list",
                grant.role()
            );
        }
    }

    // Every refusal the golden expects must be outside the generated allow set of its
    // principal, so the grants cannot pass a refused act the live-server arm checks.
    let by_role = [
        (Principal::Participant, &participant),
        (Principal::DeliveryAuthority, &delivery),
        (Principal::Bus, &bus),
        (Principal::System, &system),
        (Principal::FlowEngine, &flow_engine),
    ];
    let mut expectations = 0;
    for line in golden.lines() {
        let fields = line.split_whitespace().collect::<Vec<_>>();
        let ["expect-refused", principal, operation, subject, reason] = fields.as_slice() else {
            continue;
        };
        expectations += 1;
        let (_, grant) = by_role
            .iter()
            .find(|(candidate, _)| candidate.as_str() == *principal)
            .expect("known principal");
        let allowed = if *operation == "publish" {
            grant.publish_allow()
        } else {
            grant.subscribe_allow()
        };
        let covering = allowed
            .iter()
            .filter(|pattern| subject_matches(pattern, subject))
            .collect::<Vec<_>>();
        assert!(
            covering.is_empty(),
            "{principal} {operation} {subject} is expected refused ({reason}) but the generated grant allows it via {covering:?}"
        );
    }
    assert!(
        expectations > 0,
        "the vendored golden must carry expect-refused lines"
    );
    report(
        "passed",
        "participant, delivery-authority, bus-module, system-account and flow-engine sets equal the golden's lines",
    );
}

#[test]
fn control_partial_token_wildcard_is_refused_by_the_generator() {
    let account = grants::derive_account(PINNED_GOLDEN_FIXTURE.account).expect("account");
    let bus = grants::bus_module_grant(&account, PINNED_GOLDEN_FIXTURE.module_id).expect("bus");
    let mut entries = bus.allow_entries();
    let partial = format!("$JS.API.STREAM.INFO.CK_{}_*", account.account_upper());
    entries.push(AllowEntry {
        principal: Principal::Bus,
        operation: Operation::Publish,
        subject: partial.clone(),
    });
    let refusal = grants::Grant::from_entries(GrantRole::BusModule, &account, entries)
        .expect_err("a partial-token CK_{ACCT}_* wildcard must be refused");
    assert!(
        refusal.to_string().contains("whole subject token"),
        "the refusal must name the whole-token rule: {refusal}"
    );
}

#[test]
fn control_deny_entry_is_refused_by_the_document_validator() {
    let account = grants::derive_account(PINNED_GOLDEN_FIXTURE.account).expect("account");
    let document = grants::render_fixture_document(PINNED_GOLDEN_FIXTURE).expect("document");
    grants::validate_document(&document, &account).expect("the generated document validates");
    let with_deny = format!(
        "{document}deny participant publish {}\n",
        account.sentinel_ping()
    );
    let refusal =
        grants::validate_document(&with_deny, &account).expect_err("a deny entry must be refused");
    assert!(
        refusal.to_string().contains("deny entries are forbidden"),
        "the refusal must name the deny rule: {refusal}"
    );
}

#[test]
fn control_out_of_lexicon_account_is_refused_at_derivation() {
    let mut fixture = PINNED_GOLDEN_FIXTURE;
    fixture.account = "box_a-b";
    let refusal = grants::render_fixture_document(fixture)
        .expect_err("an out-of-lexicon account must not emit a document");
    let GrantRefusal::Generator(GrantError::Naming(naming)) = &refusal else {
        panic!("the refusal must come from account derivation, got {refusal:?}");
    };
    assert_eq!(
        naming.token(),
        "box_a-b",
        "the refusal names the offending token"
    );
    assert!(refusal.to_string().contains("box_a-b"));
    grants::derive_account("box_a_b").expect("the in-lexicon neighbour is accepted");
}

#[test]
fn vendored_foundation_and_golden_match_their_source_record() {
    let source = read_fixture("SOURCE");
    let field = |name: &str| {
        source
            .lines()
            .find_map(|line| line.strip_prefix(&format!("{name}: ")))
            .unwrap_or_else(|| panic!("SOURCE must record {name}"))
            .to_owned()
    };
    assert_eq!(
        field("source_commit"),
        "b9e827c69d98fb0c1241925961ebb5184752a25a"
    );
    // The golden is the naming crate's own reference at the pinned commons revision,
    // so it moves with the pin in Cargo.toml.
    assert_eq!(
        field("golden_commit"),
        "e4fb106f581c4d208a81e924a6329cfb20de616d"
    );
    for (file, digest_field) in [
        ("nats-message-plane-foundation.md", "source_sha256"),
        ("permission_golden.txt", "golden_sha256"),
    ] {
        let bytes = fs::read(fixture_dir().join(file)).expect("vendored file");
        let digest = Sha256::digest(&bytes)
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        assert_eq!(
            digest,
            field(digest_field),
            "{file} must match its SOURCE digest"
        );
    }
    assert!(
        read_fixture("nats-message-plane-foundation.md")
            .contains("## Amendment 2026-09-23: per-spawn credential custody"),
        "the vendored foundation must carry the credential-custody amendment"
    );
}

/// First cells of a markdown table whose header row starts with `header`.
fn table_first_cells(text: &str, header: &str) -> Vec<(String, String)> {
    let mut rows = Vec::new();
    let mut lines = text.lines().skip_while(|line| !line.starts_with(header));
    lines.next();
    for line in lines {
        if !line.starts_with('|') {
            break;
        }
        let cells = line.split('|').map(str::trim).collect::<Vec<_>>();
        if cells.len() < 3 || cells[1].starts_with("---") {
            continue;
        }
        rows.push((cells[1].to_owned(), cells[2..].join("|")));
    }
    rows
}

#[test]
fn disposition_mapping_covers_every_foundation_row() {
    let foundation = read_fixture("nats-message-plane-foundation.md");
    let mapping = read_fixture("DISPOSITION-MAPPING.md");
    let spec_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../docs/specs/ck-bus-module.md");
    let spec = fs::read_to_string(&spec_path).expect("read the ck-bus spec");
    let ladder_rows = table_first_cells(&spec, "| Ladder row |")
        .into_iter()
        .map(|(name, _)| name)
        .collect::<BTreeSet<_>>();
    assert!(
        ladder_rows.contains(ROW),
        "the spec's ladder must name this row"
    );

    let foundation_rows = table_first_cells(&foundation, "| Arm | External item |");
    assert_eq!(
        foundation_rows.len(),
        9,
        "the foundation disposition table has A1 to A9"
    );
    let mapped = table_first_cells(&mapping, "| Foundation row |");
    let acts = table_first_cells(&mapping, "| F-PROV act |");
    assert_eq!(
        acts.len(),
        5,
        "the mapping must dispose of all five F-PROV acts"
    );

    let claims_a_row = |cell: &str| {
        cell.split('`')
            .skip(1)
            .step_by(2)
            .any(|name| ladder_rows.contains(name))
    };
    for (arm, _) in &foundation_rows {
        let (_, cell) = mapped
            .iter()
            .find(|(name, _)| name == arm)
            .unwrap_or_else(|| panic!("foundation row {arm:?} is not mapped"));
        assert!(
            cell.contains("Named exclusion") || claims_a_row(cell),
            "foundation row {arm:?} must map to a ladder row or a named exclusion: {cell}"
        );
    }
    assert_eq!(
        mapped.len(),
        foundation_rows.len(),
        "the mapping has no invented rows"
    );
    for (act, cell) in &acts {
        assert!(
            claims_a_row(cell),
            "F-PROV act {act:?} must map to a ladder row: {cell}"
        );
    }
}

#[test]
fn wired_grant_seam_generates_own_user_grants_for_the_given_account_and_key() {
    use runtime::{GrantGeneration, OwnUser};
    let fixture = PINNED_GOLDEN_FIXTURE;
    let account = grants::derive_account(fixture.account).expect("pinned account derives");
    let golden = vendored_golden();
    let bus = grants::GrantSeam
        .own_user_grant(OwnUser::BusModule, &account, fixture.module_id)
        .expect("the wired seam generates the bus-module grant");
    assert_eq!(
        bus.publish,
        golden_allows(&golden, Principal::Bus, Operation::Publish)
    );
    assert_eq!(
        bus.subscribe,
        golden_allows(&golden, Principal::Bus, Operation::Subscribe)
    );
    let system = grants::GrantSeam
        .own_user_grant(OwnUser::SystemAccount, &account, fixture.system_credential)
        .expect("the wired seam generates the system-account grant");
    assert_eq!(
        system.publish,
        golden_allows(&golden, Principal::System, Operation::Publish)
    );
    assert_eq!(
        system.subscribe,
        golden_allows(&golden, Principal::System, Operation::Subscribe)
    );
    // The user key names the inbox, so a different key yields a different grant: the
    // seam really takes it as an argument.
    let other = grants::GrantSeam
        .own_user_grant(OwnUser::SystemAccount, &account, "cksysother")
        .expect("another system user key");
    assert!(other.subscribe.contains("_INBOX.cksysother.>"));
    assert_ne!(other, system);
    // A key outside the credential lexicon is refused by name, never issued.
    let refused = grants::GrantSeam
        .own_user_grant(OwnUser::BusModule, &account, "bad.key")
        .expect_err("a dotted user key must be refused");
    assert!(
        matches!(refused, runtime::GrantSeamError::Refused(_)),
        "{refused:?}"
    );
}
